int getInt(char mensaje[]);
float getFloat(char mensaje[]);
char getChar(char mensaje[]);
int getNumeroAleatorio(int desde , int hasta, int iniciar);
void CualquierTeclaContinnuar (void);
void getString(char mensaje[],char arrayChar[]);
int getNumeroAleatorio(int desde, int hasta, int iniciar);
int esNumeroChar (char num[]);
int getNumerosChar (char array[],char mensaje[]);
int esSoloLetras(char array[]);
